spring:
  profiles:
    active: local

  config:
    import: ./privates/application-oauth.yml, ./privates/application-api-key.yml

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    show-sql: true
    properties:
      hibernate:
      format_sql: true

  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace